# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetToolInstaller@0
  inputs:
   checkLatest: true
- pwsh: |
     Get-Command mvn
  displayName: 'Installing Maven'
- pwsh: |
      $buildNumber = 0      
      if($env:APPVEYOR_REPO_TAG -eq "true") {
       $buildNumber = $(Build.SourceBranchName)
       Write-Host “Found git tag."
      } 
      else {
       $buildNumber = "1.5.0-SNAPSHOT-$(Build.BuildId)"
       Write-Host “git tag not found. Setting package suffix to '$buildNumber'"
      }     
      .\package.ps1 -buildNumber $buildNumber
  displayName: 'Executing build script'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/pkg'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  displayName: 'Copying files for artifacts'
- pwsh: |
      .\setup-tests.ps1
  displayName: 'Setting tests'
- pwsh: |
      Compress-Archive -Path $(System.DefaultWorkingDirectory)\endtoendtests\target\azure-functions\azure-functions-java-endtoendtests\* -DestinationPath $(System.DefaultWorkingDirectory)\endtoendtests\e2etestsjava.zip
  displayName: 'Create test app zip file'
- pwsh: |
    Install-Module Az.Storage -Force -Verbose -Scope CurrentUser
    if (-not (Get-command new-azstoragecontext -ea SilentlyContinue))
    {
      throw "new-azstoragecontext is not present"
    }
    $localFile = '$(System.DefaultWorkingDirectory)\endtoendtests\e2etestsjava.zip'
    if (Test-Path $localFile)
    {
      Write-Host "File exists"
    } 
    $blobName = 'e2etestsjava.zip'
    $Context = New-AzStorageContext -StorageAccountName $(StorageAccountName) -StorageAccountKey $(StorageAccountKey)
    Set-AzStorageBlobContent -File $localFile -Container $(ContainerName) -Blob $blobName -Context $Context  -Force
  env:
    AzureFunctionsE2ETestStorage: $(AzureFunctionsE2ETestStorage)
  displayName: 'Copying test app zip artifacts to blob'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publishing build and test result artifacts'