# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- pwsh: |
     Get-Command mvn
     Get-Command nuget
- pwsh: |
      $buildNumber = 0      
      if($env:APPVEYOR_REPO_TAG -eq "true") {
       $buildNumber = $(Build.SourceBranchName)
       Write-Host “Found git tag."
      } 
      else {
       $buildNumber = "1.5.0-SNAPSHOT-$(devops_buildNumber)"
       Write-Host “git tag not found. Setting package suffix to '$buildNumber'"
      }     
      .\package.ps1 -buildNumber $buildNumber
  env:
    AzureWebJobsStorage: $(AzureWebJobsStorage)
    AzureWebJobsCosmosDBConnectionString: $(AzureWebJobsCosmosDBConnectionString)
    AzureWebJobsServiceBus: $(AzureWebJobsServiceBus)
    AzureWebJobsEventHubReceiver: $(AzureWebJobsEventHubReceiver)
    AzureWebJobsEventHubSender: $(AzureWebJobsEventHubSender)
    AzureWebJobsEventHubPath: $(AzureWebJobsEventHubPath)
    SBTopicName: $(SBTopicName)
    SBTopicSubName: $(SBTopicSubName)
    CosmosDBDatabaseName: $(CosmosDBDatabaseName)
    SBQueueName: $(SBQueueName)
  displayName: 'Executing build script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
